<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<Title>InvoiceVault.Infrastructure</Title>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>  
	<PackageId>InvoiceVault.Infrastructure</PackageId>  
	<Version>1.0.0</Version>  
	<Authors>Erp Systems Sp. z.o.o</Authors>
	<Product>InvoiceVault</Product>
	<IsPackable>true</IsPackable>
	<GenerateAppxPackageOnBuild>true</GenerateAppxPackageOnBuild>
	<PackageOutputPath>D:\Bogumił\InvoiceVault\InvoiceVault\Packages</PackageOutputPath>
  </PropertyGroup>

</Project>
